# Cargo config file.
# See https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set to all `cargo ...` commands.
[env]

# Scope down trancing, to filter out external lib tracing.
RUST_LOG="rust_web_app=debug"

# -- Service Environment Variables
# IMPORTANT:
#   For cargo commands only.
#   For deploye env, should be managed by container.
#   (e.g., Kuberetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost/app_db"

## -- ConfigMap

SERVICE_WEB_FOLDER="web-folder/"